In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
plt.style.use("seaborn-v0_8")

import seaborn as sns
sns.set_style("darkgrid")

%config InlineBackened.format_figure = "svg"

In [3]:
import tensorflow as tf

In [4]:
path_to_file = "shakespeare.txt"

In [5]:
text = open(file = path_to_file, mode = 'r').read()

In [6]:
text[:500]

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [7]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [8]:
print(text[4500:4800])

converted are
  From his low tract and look another way:
    So thou, thy self out-going in thy noon:
    Unlooked on diest unless thou get a son.


                     8
  Music to hear, why hear'st thou music sadly?
  Sweets with sweets war not, joy delights in joy:
  Why lov'st thou that which t


In [9]:
vocab = sorted(set(text))
vocab

['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}']

In [10]:
len(vocab)

84

In [11]:
for pair in enumerate(vocab):
    print(pair)

(0, '\n')
(1, ' ')
(2, '!')
(3, '"')
(4, '&')
(5, "'")
(6, '(')
(7, ')')
(8, ',')
(9, '-')
(10, '.')
(11, '0')
(12, '1')
(13, '2')
(14, '3')
(15, '4')
(16, '5')
(17, '6')
(18, '7')
(19, '8')
(20, '9')
(21, ':')
(22, ';')
(23, '<')
(24, '>')
(25, '?')
(26, 'A')
(27, 'B')
(28, 'C')
(29, 'D')
(30, 'E')
(31, 'F')
(32, 'G')
(33, 'H')
(34, 'I')
(35, 'J')
(36, 'K')
(37, 'L')
(38, 'M')
(39, 'N')
(40, 'O')
(41, 'P')
(42, 'Q')
(43, 'R')
(44, 'S')
(45, 'T')
(46, 'U')
(47, 'V')
(48, 'W')
(49, 'X')
(50, 'Y')
(51, 'Z')
(52, '[')
(53, ']')
(54, '_')
(55, '`')
(56, 'a')
(57, 'b')
(58, 'c')
(59, 'd')
(60, 'e')
(61, 'f')
(62, 'g')
(63, 'h')
(64, 'i')
(65, 'j')
(66, 'k')
(67, 'l')
(68, 'm')
(69, 'n')
(70, 'o')
(71, 'p')
(72, 'q')
(73, 'r')
(74, 's')
(75, 't')
(76, 'u')
(77, 'v')
(78, 'w')
(79, 'x')
(80, 'y')
(81, 'z')
(82, '|')
(83, '}')


In [12]:
ind_to_char = {ind:char for ind,char in enumerate(vocab)}
ind_to_char

{0: '\n',
 1: ' ',
 2: '!',
 3: '"',
 4: '&',
 5: "'",
 6: '(',
 7: ')',
 8: ',',
 9: '-',
 10: '.',
 11: '0',
 12: '1',
 13: '2',
 14: '3',
 15: '4',
 16: '5',
 17: '6',
 18: '7',
 19: '8',
 20: '9',
 21: ':',
 22: ';',
 23: '<',
 24: '>',
 25: '?',
 26: 'A',
 27: 'B',
 28: 'C',
 29: 'D',
 30: 'E',
 31: 'F',
 32: 'G',
 33: 'H',
 34: 'I',
 35: 'J',
 36: 'K',
 37: 'L',
 38: 'M',
 39: 'N',
 40: 'O',
 41: 'P',
 42: 'Q',
 43: 'R',
 44: 'S',
 45: 'T',
 46: 'U',
 47: 'V',
 48: 'W',
 49: 'X',
 50: 'Y',
 51: 'Z',
 52: '[',
 53: ']',
 54: '_',
 55: '`',
 56: 'a',
 57: 'b',
 58: 'c',
 59: 'd',
 60: 'e',
 61: 'f',
 62: 'g',
 63: 'h',
 64: 'i',
 65: 'j',
 66: 'k',
 67: 'l',
 68: 'm',
 69: 'n',
 70: 'o',
 71: 'p',
 72: 'q',
 73: 'r',
 74: 's',
 75: 't',
 76: 'u',
 77: 'v',
 78: 'w',
 79: 'x',
 80: 'y',
 81: 'z',
 82: '|',
 83: '}'}

In [13]:
char_to_ind = {char:ind for ind , char in enumerate(vocab)}
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '|': 82,
 '}': 83}

In [14]:
print(text[:100])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose mi


In [15]:
encoded_text = np.array([char_to_ind[c] for c in text])
encoded_text

array([ 0,  1,  1, ..., 30, 39, 29], shape=(5445609,))

In [16]:
text_splitter = 23
text[:text_splitter]

'\n                     1'

In [17]:
encoded_text[:text_splitter]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12])

In [18]:
sample = text[:500]
sample

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [19]:
encoded_text[:500]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75,  1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63,
       70, 76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60,
       56, 74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,
        1, 63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1,
       63, 64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,
        1, 75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1,
       75, 70,  1, 75, 63

In [20]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [21]:
lines = "From fairest creatures we desire increase"
lines

'From fairest creatures we desire increase'

In [22]:
len(lines)

41

In [23]:
seq_len = 120 # length of the training sequences


In [24]:
len(text)

5445609

In [25]:
total_num_seq = len(text) // (seq_len+1) # I make my guess for it to be considered as number of batches.
total_num_seq

45005

In [26]:
# Tensorflow has a library that provides all the recent steps we have done: 
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)
char_dataset , type(char_dataset)

(<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>,
 tensorflow.python.data.ops.from_tensor_slices_op._TensorSliceDataset)

In [27]:
for item in char_dataset.take(20): #analogous to text[:20]
    print(item)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)


In [28]:
for item in char_dataset.take(20): #analogous to text[:20]
    print(item.numpy())


0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


In [29]:
for item in char_dataset.take(20): #analogous to text[:20]
    #characters = [ind_to_char[int(idx)] for idx in item.numpy()]
    print(ind_to_char[int(item.numpy())])

In [30]:
sequences = char_dataset.batch(seq_len + 1 , drop_remainder = True)
sequences

<_BatchDataset element_spec=TensorSpec(shape=(121,), dtype=tf.int64, name=None)>

In [31]:
def create_seq_targets(seq): # seq = "Hello my name"
    input_txt = seq[:-1] # Hello my nam"
    target_txt = seq[1:] # ello my name"
    return input_txt , target_txt

In [32]:
seq_len

120

In [33]:
dataset = sequences.map(create_seq_targets)
dataset.take(1)

<_TakeDataset element_spec=(TensorSpec(shape=(120,), dtype=tf.int64, name=None), TensorSpec(shape=(120,), dtype=tf.int64, name=None))>

In [34]:
for input_txt , target_txt in dataset.take(1):
    print(input_txt.numpy())
    input_chars = [ind_to_char[int(idx)] for idx in input_txt.numpy()]
    print("".join(input_chars))
    print('\n')
    print(target_txt.numpy())
    target_chars = [ind_to_char[int(idx)] for idx in target_txt.numpy()]
    print("".join(target_chars))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


In [35]:
batch_size = 128
buffer_size = 10000
dataset = dataset.shuffle(buffer_size).batch(batch_size , drop_remainder=True)

In [36]:
dataset

<_BatchDataset element_spec=(TensorSpec(shape=(128, 120), dtype=tf.int64, name=None), TensorSpec(shape=(128, 120), dtype=tf.int64, name=None))>

Buiding the model

In [37]:
vocab_size = len(vocab)
vocab_size

84

In [38]:
embed_dim = 64
rnn_neurons = 1026

In [39]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [40]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module keras.src.losses.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, ignore_class=None, axis=-1)
    Computes the sparse categorical crossentropy loss.
    
    Args:
        y_true: Ground truth values.
        y_pred: The predicted values.
        from_logits: Whether `y_pred` is expected to be a logits tensor. By
            default, we assume that `y_pred` encodes a probability distribution.
        ignore_class: Optional integer. The ID of a class to be ignored during
            loss computation. This is useful, for example, in segmentation
            problems featuring a "void" class (commonly -1 or 255) in
            segmentation maps. By default (`ignore_class=None`), all classes are
            considered.
        axis: Defaults to `-1`. The dimension along which the entropy is
            computed.
    
    Returns:
        Sparse categorical crossentropy loss value.
    
    Examples:
    


In [41]:
def sparse_cat_loss(y_true , y_pred):
    return sparse_categorical_crossentropy(y_true , y_pred , from_logits=True)

In [42]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding , GRU, Dense

In [43]:
def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    model = Sequential()
    model.add(tf.keras.layers.InputLayer(batch_input_shape=(batch_size, None)))
    model.add(Embedding(vocab_size, embed_dim))
    model.add(GRU(
        rnn_neurons,
        return_sequences=True,
        stateful=True,
        recurrent_initializer='glorot_uniform'))
    model.add(Dense(vocab_size))
    model.compile(optimizer='adam', loss=sparse_cat_loss)
    return model

In [44]:
model = create_model(vocab_size=vocab_size , 
                     embed_dim=embed_dim , 
                     rnn_neurons=rnn_neurons , 
                     batch_size=batch_size)
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (128, None, 64)        │         5,376 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ (128, None, 1026)      │     3,361,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (128, None, 84)        │        86,268 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,452,820 (13.17 MB)

 Trainable params: 3,452,820 (13.17 MB)

 Non-trainable params: 0 (0.00 B)

In [45]:
for input_example_batch , target_example_batch in dataset.take(1):
    example_batch_predictions = model(input_example_batch)


In [46]:
example_batch_predictions.shape

TensorShape([128, 120, 84])

In [47]:
example_batch_predictions[0]

<tf.Tensor: shape=(120, 84), dtype=float32, numpy=
array([[ 3.1012949e-03,  3.1809441e-03,  2.5445167e-03, ...,
         2.2193813e-03,  2.1786594e-03,  1.2876305e-03],
       [ 3.5247236e-04, -5.4561310e-03, -3.5529404e-03, ...,
         2.1695185e-03, -4.2223125e-03,  1.8749369e-03],
       [-4.8775678e-03,  1.8347115e-03,  1.0776584e-03, ...,
         1.4564903e-04, -9.1742404e-04, -2.1571494e-03],
       ...,
       [ 3.4558091e-03,  3.2568772e-03,  3.0216237e-03, ...,
         8.3711334e-03, -6.5917196e-03,  1.0752467e-03],
       [-2.5936186e-03, -8.0827810e-03,  1.9586759e-04, ...,
         3.1821497e-03, -6.4144697e-06,  1.8696714e-03],
       [ 1.7724116e-03, -2.0757637e-03,  2.5559349e-03, ...,
         3.3622980e-03,  2.8424344e-03,  2.8555705e-03]],
      shape=(120, 84), dtype=float32)>

In [48]:
example_batch_predictions[0].numpy().reshape(1,-1)

array([[0.00310129, 0.00318094, 0.00254452, ..., 0.0033623 , 0.00284243,
        0.00285557]], shape=(1, 10080), dtype=float32)

In [50]:
sampled_indices = tf.random.categorical(logits=example_batch_predictions[0], num_samples=1)
sampled_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[34],
       [74],
       [21],
       [55],
       [48],
       [20],
       [21],
       [10],
       [44],
       [66],
       [50],
       [70],
       [61],
       [43],
       [41],
       [79],
       [63],
       [17],
       [39],
       [57],
       [ 3],
       [67],
       [63],
       [20],
       [ 5],
       [77],
       [ 5],
       [24],
       [10],
       [64],
       [60],
       [44],
       [78],
       [66],
       [ 1],
       [66],
       [ 6],
       [ 5],
       [ 5],
       [21],
       [ 8],
       [12],
       [74],
       [75],
       [19],
       [30],
       [19],
       [ 2],
       [28],
       [50],
       [74],
       [59],
       [62],
       [28],
       [70],
       [73],
       [ 1],
       [17],
       [28],
       [48],
       [54],
       [54],
       [25],
       [68],
       [64],
       [35],
       [64],
       [50],
       [28],
       [82],
       [58],
       [73],
       [80],
   

In [51]:
sampled_indices = tf.squeeze(sampled_indices , axis = -1).numpy()
sampled_indices

array([34, 74, 21, 55, 48, 20, 21, 10, 44, 66, 50, 70, 61, 43, 41, 79, 63,
       17, 39, 57,  3, 67, 63, 20,  5, 77,  5, 24, 10, 64, 60, 44, 78, 66,
        1, 66,  6,  5,  5, 21,  8, 12, 74, 75, 19, 30, 19,  2, 28, 50, 74,
       59, 62, 28, 70, 73,  1, 17, 28, 48, 54, 54, 25, 68, 64, 35, 64, 50,
       28, 82, 58, 73, 80, 12, 69, 65, 32, 36, 25, 76, 60, 50, 12, 73, 58,
        2, 37, 79, 29,  6, 36, 45, 16,  3,  0, 52, 50, 80, 51, 13, 32, 49,
       31, 76, 35,  6, 69, 24, 10, 26, 81, 66,  7, 48, 62, 30, 73,  7, 25,
       60])

In [56]:
np.array([ind_to_char[char] for char in sampled_indices])

array(['I', 's', ':', '`', 'W', '9', ':', '.', 'S', 'k', 'Y', 'o', 'f',
       'R', 'P', 'x', 'h', '6', 'N', 'b', '"', 'l', 'h', '9', "'", 'v',
       "'", '>', '.', 'i', 'e', 'S', 'w', 'k', ' ', 'k', '(', "'", "'",
       ':', ',', '1', 's', 't', '8', 'E', '8', '!', 'C', 'Y', 's', 'd',
       'g', 'C', 'o', 'r', ' ', '6', 'C', 'W', '_', '_', '?', 'm', 'i',
       'J', 'i', 'Y', 'C', '|', 'c', 'r', 'y', '1', 'n', 'j', 'G', 'K',
       '?', 'u', 'e', 'Y', '1', 'r', 'c', '!', 'L', 'x', 'D', '(', 'K',
       'T', '5', '"', '\n', '[', 'Y', 'y', 'Z', '2', 'G', 'X', 'F', 'u',
       'J', '(', 'n', '>', '.', 'A', 'z', 'k', ')', 'W', 'g', 'E', 'r',
       ')', '?', 'e'], dtype='<U1')

In [58]:
epochs = 30


In [61]:
#model.fit(dataset , epochs=epochs) 
# # it takes much time, so we will load it from tensorflow

In [64]:
from tensorflow.keras.models import load_model

In [65]:
model2 = create_model(vocab_size , embed_dim, rnn_neurons , batch_size=1)
model2.load_weights('shakespeare_gen.h5')
model2.build(tf.TensorShape([1,None]))

In [66]:
model2.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (1, None, 64)          │         5,376 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_1 (GRU)                     │ (1, None, 1026)        │     3,361,176 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (1, None, 84)          │        86,268 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,452,820 (13.17 MB)

 Trainable params: 3,452,820 (13.17 MB)

 Non-trainable params: 0 (0.00 B)

In [76]:
def generate_text(model , start_seed , gen_size = 500 , temp = 0.1):
    num_generate = gen_size
    input_eval = [char_to_ind[s] for s in start_seed]
    input_eval = tf.expand_dims(input_eval,0)
    text_generated = []
    temperature = temp

    model.layers[1].reset_states()

    for i in range(num_generate):
        predictions = model(input_eval)
        predictions = tf.squeeze(predictions,0)
        predictions = predictions/temperature
        predicted_id = tf.random.categorical(logits=predictions,num_samples=1)[-1,0].numpy()
        input_eval = tf.expand_dims([predicted_id],0)
        text_generated.append(ind_to_char[predicted_id])
    
    return (start_seed + "".join(text_generated))

In [78]:
print(generate_text(model2, start_seed="JULIET", gen_size=1000))

JULIETHET. And I will with thee there was such a word;
    But since you know his noble cousin work,
    The sharpest of the state of war with sweet,
    Which is a strange to use it for a wife
    That we may prove upon the holy prince,
    And with the happier man should be the man.
    The King is come to speak with me to seek the Queen.
    And therefore have I done that thou shalt have,
    The sea and land I have to say is strange.
    But this is so, my lord, I say the third is so.
    There is no trust or see the manner of his wife.
    I think he will not have them not to bear his face,
    That she shall be my country's bower.
    The King is come to speak with me to seek the Queen.
  GLOUCESTER. Why, then we shall have me for this town?
  PETRUCHIO. I thank your Grace, I am a gentleman.
    The King is not at hand, and then I speak
    What we shall have the highest creature that
    Which they have seen the charge of this shall ever
    Profess'd to hear thee speak a word w